### ISSUE TITLE
[RU05] Poder clonar código

### ISSUE THREAD

**Issue by elbraulio** [samhv/jedit_cc4401#10]
[Sam Hernández y Pablo Bustamante]

Permitir hacer un clon del código en el repositorio con un botón.
- Iteración 1
  - [x] RS05-01 Crear interfaz en el tabspanel para Clonar https://github.com/samhv/jedit_cc4401/issues/40
    - [x] RS05-01-01 Agregar botón físico en el Tabs Panel de la ventana de GitHub https://github.com/samhv/jedit_cc4401/issues/54
    - [x] RS05-01-02 Agregar EditText para ingresar la url del repo a clonar. https://github.com/samhv/jedit_cc4401/issues/53
    - [x] RS05-01-03 Agregar EditText para ingresar el path local donde guardar el proyecto.
      https://github.com/samhv/jedit_cc4401/issues/41
    - [x] RS05-01-04 Agregar Botón que inicie la  clonación del proyecto. https://github.com/samhv/jedit_cc4401/issues/55
- Iteración 2
  - [x] RS05-03 Implementar método para clonar de github.
    https://github.com/samhv/jedit_cc4401/issues/42
  - [x] RS05-04 Crear conexión entre el botón y el método creado.
    https://github.com/samhv/jedit_cc4401/issues/43
- Iteración 3
  - [x] RS05-05 Incluir plugin y sus dependencias al proyecto jedit. https://github.com/samhv/jedit_cc4401/issues/72

**Comment by samhv** [comment]
Api github para java.
http://github-api.kohsuke.org/source-repository.html

**Comment by samhv** [comment]
Ejemplo de cómo hacer clon desde java.
https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/CloneRemoteRepository.java
