### ISSUE TITLE
[RU16] Seleccionar proyecto

### ISSUE THREAD

**Issue by ppbustamante** [samhv/jedit_cc4401#12]
Permitir seleccionar un proyecto con clases java para realizar el análisis con JRipples con una ventana emergente.
**Edit**
- Iteración 2:
  - [X] [RS16-01] Crear mockup de ventana para seleccionar proyecto/carpeta con clases Java (#66)
  - [X] [RS16-02] Integrar funcionalidad de ventana de selección de proyectos al plugin de JRipples (#70) 
- Iteración 3:
  - [ ] [RS16-03] Invocar applicación de JRipples desde la ventana de selección de proyectos (#71)
