### ISSUE TITLE
[RU06] Poder hacer commit y push

### ISSUE THREAD

**Issue by elbraulio** [samhv/jedit_cc4401#13]
[Sam Hernández y Pablo Bustamante]

Se debe permitir tener los botones para subir el código de manera local o a la rama maestra.
- Iteración 1
  - [x] RS06-01 Crear interfaz para la funcionalidad Commit
    - [x] RS06-01-01 Agregar tabs en el tabspanel para hacer commit.
      https://github.com/samhv/jedit_cc4401/issues/58
    - [x] RS06-01-02 Agregar EditText para ingresar el comentario del commit.
      https://github.com/samhv/jedit_cc4401/issues/45
    - [x] RS06-01-03 Agregar Botón en el tabs panel para realizar el commit. https://github.com/samhv/jedit_cc4401/issues/56
  - [x] RS06-02 Crear interfaz para la funcionalidad Push https://github.com/samhv/jedit_cc4401/issues/46
    - [x] RS06-02-01 Agregar tabs en el tabspanel para hacer push.
      https://github.com/samhv/jedit_cc4401/issues/44
    - [x] RS06-02-02 Agregar Botón en el tabs panel para realizar el push. https://github.com/samhv/jedit_cc4401/issues/57
- Iteración 2
  - [x] RS06-04 Implementar método para hacer commit en github desde java.
    https://github.com/samhv/jedit_cc4401/issues/47
  - [x] RS06-05 Implementar método para hacer push en github desde java.
    https://github.com/samhv/jedit_cc4401/issues/48
  - [x] RS06-06 Crear conexión entre el botón commit y el método creado para commit.
    https://github.com/samhv/jedit_cc4401/issues/51
  - [x] RS06-07 Crear conexión entre el botón push y el método creado para push.
    https://github.com/samhv/jedit_cc4401/issues/49
- Iteración 3
  - [x] RS06-08 Agregar boton push en ventana Commit Manager
    https://github.com/samhv/jedit_cc4401/issues/50

**Comment by samhv** [comment]
Api github-java
http://github-api.kohsuke.org

La clase GHCommit puede servir.

**Comment by samhv** [comment]
Aqui hablan de cómo hacer commit y push desde java:
http://stackoverflow.com/questions/11801983/how-to-create-a-commit-and-push-into-repo-with-github-api-v3

Aqui hablan del push en java:
http://stackoverflow.com/questions/13446842/how-do-i-do-git-push-with-jgit

**Comment by samhv** [comment]
Se añadió EventBus al proyecto, con esto es fácil mantener un código desacoplado y ademas poder trabajar por separad. La implementación fue hecha también para https://github.com/samhv/jedit_cc4401/issues/10, y https://github.com/samhv/jedit_cc4401/issues/4.

Con EventBus la conexión entre las vistas y la lógica GitHub se hace simple, permite el desacoplamiento y ademas aumenta la calidad al código ya que disminuye la dificultad de extender y cambiar funcionalidades fácilmente.

**Comment by raimilcruz** [comment]
Recordar que cuando se adicione una nueva libreria al proyecto del plugin se debe incluir en el build.xml del plugin (JGitPlugin). En este caso adicione guava al build.xml (commit https://github.com/raimil-cruz/jgitplugin/commit/a39f1d76a9ccbe93e6d6421be30d4641143c6496)
