### ISSUE TITLE
[RU04] Poder hacer login en GitHub

### ISSUE THREAD

**Issue by elbraulio** [samhv/jedit_cc4401#4]
[Sam Hernández y Pablo Bustamante]

Interfaz o enlace en la barra de herramientas que permita conectarse a un repositorio GitHub.
- Iteración 1
  - [x] RS04-01 Agregar botón físico en la barra de herramientas https://github.com/samhv/jedit_cc4401/issues/19
  - [x] RS04-02 Crear interfaz gráfica (panel) para logearse con la API de GitHub https://github.com/samhv/jedit_cc4401/issues/20
    - [x] RS04-02-01 Crear ventana contenedora para la interfaz. https://github.com/samhv/jedit_cc4401/issues/59
    - [x] RS04-02-02 Crear TextFields para ingresar nombre de usuario GitHub. https://github.com/samhv/jedit_cc4401/issues/60
    - [x] RS04-02-03 Crear TextFields para ingresar contraseña de usuario GitHub. https://github.com/samhv/jedit_cc4401/issues/63
    - [x] RS04-02-04 Crear botones Aceptar y Cancelar en la interfaz. https://github.com/samhv/jedit_cc4401/issues/62
- Iteración 2
  - [x] RS04-03 Crear Clases para la conexión a GitHub con la Api de la misma.  https://github.com/samhv/jedit_cc4401/issues/26
  - [x] RS04-04 Crear conexión entre el botón Aceptar y la clase creada. https://github.com/samhv/jedit_cc4401/issues/28
- Iteración 3
  - [x] Luego de conectarse, guardar o no las credenciales, según la decision del usuario https://github.com/samhv/jedit_cc4401/issues/33

**Comment by samhv** [comment]
Api github con java:
http://github-api.kohsuke.org

Tal vez las clases GHAuthorization y GHUser puedan servir.

**Comment by ppbustamante** [comment]
Se encontró un archivo en el directorio del proyecto jEdit llamado "jedit_gui.props" el cual posee los menús, los nombres y los íconos  asociados.

**Comment by samhv** [comment]
Api de github (original)
https://developer.github.com/v3/

Api O/O, pero solo permite hacer cosas remotas; no locales.
http://github-api.kohsuke.org

Api O/O con cosas remotas y locales, la ocupa eclipse.
http://wiki.eclipse.org/JGit/User_Guide
