### ISSUE TITLE
[RU07]  Boton para reportar "issues"

### ISSUE THREAD

**Issue by samhv** [samhv/jedit_cc4401#5]
Botón para reportar los problemas con GitHub
**Edit:** Actualización de los requisitos de software en cada iteración. El requisito consiste en adicionar un "botón" para reportar issues. Otras tareas fueron realizadas en el contexto de este requisito de usuario como visualizar lista de issues, crear labels y visualizar lista de labels
- Iteración 1
  - [X] [RS07-01] Agregar opción "report issue" a la interfaz de JEdit  (#37)
  - [X] [RS07-02] Diseñar y crear ventana de reportar issue (#38)
    - [X] Creación de un ventana para crear issues (#38)
    - [X] Creación de una ventana para visualizar issues (#38)
  - [X] [RS07-03] Implementar comunicación con GitHub para reportar issue (#39)
    - [X] Creación de un proyecto Java (de prueba) para probar funcionalidades de crear y visualizar  issues ([Issue Manager](https://github.com/raimil-cruz/jedit-issues-mgr))

Los trabajos en la iteración 2 fueron realizados en su mayoría el repositorio [JGitPlugin](https://github.com/raimil-cruz/jgitplugin)
- Iteración 2
  - [X] [RS07-04] Integrar funcionalidad de Issues con el resto de las funcionalidades con GitHub (#52) 
  - [X] [RS07-05] Crear plugin para JEdit para integrar funcionalidades de Git (#68) 
  - [X] [RS07-06] Crear ventanas para adicionar y visualizar labels (#69)

**Comment by raimilcruz** [comment]
Las funcionalidades deseadas para este requisito han sido completadas. Estas funcionalidad fueron implementadas de manera total en el proyecto [JGitPlugin](https://github.com/raimil-cruz/jgitplugin)
