### ISSUE TITLE
[RU11] Mover tabs

### ISSUE THREAD

**Issue by jampueroc** [samhv/jedit_cc4401#7]
Permitir generar una nueva pestaña al abrir otro archivo.
- Iteracion 1
  - [x] Diseñar una tab https://github.com/samhv/jedit_cc4401/issues/21
  - [x] Crear un panel que permita ver varias tabs https://github.com/samhv/jedit_cc4401/issues/24
  - [x] Permitir cerrar tabs https://github.com/samhv/jedit_cc4401/issues/27
  - [x] Localizar el lugar donde se insertará esta tab en JEdit
- Iteracion 2
  - [ ] Permitir mover tabs en el panel https://github.com/samhv/jedit_cc4401/issues/25
  - [x] Añadir el panel de tabs a jedit https://github.com/samhv/jedit_cc4401/issues/29
  - [x] Al abrir un archivo debe aparecer un tab con el nombre del archivo https://github.com/samhv/jedit_cc4401/issues/30
- Iteracion 3
  - [x] Agregar método de overflow a tabs. https://github.com/samhv/jedit_cc4401/issues/67
  - [x] Al seleccionar un tab debe cambiar el foco https://github.com/samhv/jedit_cc4401/issues/31
  - [x] Al cerrar un tab debe cerrar el archivo https://github.com/samhv/jedit_cc4401/issues/32

**Comment by hfehrmann** [comment]
Este requisito no se cumple
